In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("customer_journey.csv")

print("Dataset loaded successfully.")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully.
Shape: (12719, 10)

,SessionID,UserID,Timestamp,PageType,DeviceType,Country,ReferralSource,TimeOnPage_seconds,ItemsInCart,Purchased
0,session_0,user_2223,2025-01-20 22:53:34,home,Desktop,India,Social Media,55,0,0
1,session_1,user_2192,2025-02-26 12:57:10,home,Tablet,Germany,Email,99,0,0
2,session_1,user_2192,2025-02-26 12:59:11,product_page,Tablet,Germany,Email,121,0,0
3,session_2,user_1708,2025-06-24 15:40:46,home,Mobile,India,Google,160,0,0
4,session_3,user_2976,2025-06-11 07:21:02,home,Tablet,UK,Google,113,0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12719 entries, 0 to 12718
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SessionID           12719 non-null  object
 1   UserID              12719 non-null  object
 2   Timestamp           12719 non-null  object
 3   PageType            12719 non-null  object
 4   DeviceType          12719 non-null  object
 5   Country             12719 non-null  object
 6   ReferralSource      12719 non-null  object
 7   TimeOnPage_seconds  12719 non-null  int64
 8   ItemsInCart         12719 non-null  int64
 9   Purchased           12719 non-null  int64
dtypes: int64(3), object(7)
memory usage: 993.8+ KB

In [4]:
df.describe(include='all')

,SessionID,UserID,Timestamp,PageType,DeviceType,Country,ReferralSource,TimeOnPage_seconds,ItemsInCart,Purchased
count,12719,12719,12719,12719,12719,12719,12719,12719.000000,12719.000000,12719.000000
unique,5000,1872,12713,5,3,7,4,NaN,NaN,NaN
top,session_3728,user_2012,2025-02-19 08:50:27,home,Mobile,France,Google,NaN,NaN,NaN
freq,5,27,2,5000,4256,1980,3304,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.427707,1.138533,0.397044
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.120729,1.689954,0.489304
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.000000,2.000000,1.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.000000,5.000000,1.000000

In [5]:
df.isnull().sum()

SessionID             0
UserID                0
Timestamp             0
PageType              0
DeviceType            0
Country               0
ReferralSource        0
TimeOnPage_seconds    0
ItemsInCart           0
Purchased             0
dtype: int64

In [6]:
duplicate_count = df.duplicated().sum()
print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [7]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['sessionid', 'userid', 'timestamp', 'pagetype', 'devicetype', 'country',
       'referralsource', 'timeonpage_seconds', 'itemsincart', 'purchased'],
      dtype='object')

In [8]:
df = df.rename(columns={
    'sessionid': 'session_id',
    'userid': 'user_id',
    'timestamp': 'timestamp',
    'pagetype': 'page_type',
    'devicetype': 'device_type',
    'country': 'country',
    'referralsource': 'referral_source',
    'timeonpage_seconds': 'time_on_page_seconds',
    'itemsincart': 'items_in_cart',
    'purchased': 'purchased'})
df.columns

Index(['session_id', 'user_id', 'timestamp', 'page_type', 'device_type',
       'country', 'referral_source', 'time_on_page_seconds', 'items_in_cart',
       'purchased'],
      dtype='object')

In [9]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df['timestamp'].head()

0   2025-01-20 22:53:34
1   2025-02-26 12:57:10
2   2025-02-26 12:59:11
3   2025-06-24 15:40:46
4   2025-06-11 07:21:02
Name: timestamp, dtype: datetime64[ns]

In [10]:
df['timestamp'].isnull().sum()

np.int64(0)

In [11]:
df = df.sort_values(by=['session_id', 'timestamp']).reset_index(drop=True)
df.head(20)

,session_id,user_id,timestamp,page_type,device_type,country,referral_source,time_on_page_seconds,items_in_cart,purchased
0,session_0,user_2223,2025-01-20 22:53:34,home,Desktop,India,Social Media,55,0,0
1,session_1,user_2192,2025-02-26 12:57:10,home,Tablet,Germany,Email,99,0,0
2,session_1,user_2192,2025-02-26 12:59:11,product_page,Tablet,Germany,Email,121,0,0
3,session_10,user_2357,2025-05-17 22:11:37,home,Tablet,India,Direct,75,0,0
4,session_10,user_2357,2025-05-17 22:13:33,product_page,Tablet,India,Direct,116,0,0
5,session_100,user_1233,2025-04-02 11:24:36,home,Desktop,USA,Email,36,0,0
6,session_100,user_1233,2025-04-02 11:25:41,product_page,Desktop,USA,Email,65,1,0
7,session_1000,user_1551,2025-08-25 09:34:15,home,Mobile,France,Email,45,0,1
8,session_1000,user_1551,2025-08-25 09:35:45,product_page,Mobile,France,Email,90,3,1
9,session_1000,user_1551,2025-08-25 09:38:16,cart,Mobile,France,Email,151,3,1
10,session_1000,user_1551,2025-08-25 09:40:48,checkout,Mobile,France,Email,152,3,1
11,session_1000,user_1551,2025-08-25 09:41:24,confirmation,Mobile,France,Email,36,0,1
12,session_1001,user_2877,2025-03-27 20:11:23,home,Desktop,Germany,Direct,145,0,0
13,session_1001,user_2877,2025-03-27 20:13:05,product_page,Desktop,Germany,Direct,102,5,0
14,session_1001,user_2877,2025-03-27 20:13:22,cart,Desktop,Germany,Direct,17,5,0
15,session_1002,user_1834,2025-02-11 10:53:09,home,Mobile,Canada,Direct,98,0,1
16,session_1002,user_1834,2025-02-11 10:53:30,product_page,Mobile,Canada,Direct,21,3,1
17,session_1002,user_1834,2025-02-11 10:55:15,cart,Mobile,Canada,Direct,105,3,1
18,session_1002,user_1834,2025-02-11 10:56:50,checkout,Mobile,Canada,Direct,95,3,1
19,session_1002,user_1834,2025-02-11 10:58:53,confirmation,Mobile,Canada,Direct,123,0,1

In [12]:
text_cols = ['page_type', 'device_type', 'country', 'referral_source']
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()
df.head()

,session_id,user_id,timestamp,page_type,device_type,country,referral_source,time_on_page_seconds,items_in_cart,purchased
0,session_0,user_2223,2025-01-20 22:53:34,home,desktop,india,social media,55,0,0
1,session_1,user_2192,2025-02-26 12:57:10,home,tablet,germany,email,99,0,0
2,session_1,user_2192,2025-02-26 12:59:11,product_page,tablet,germany,email,121,0,0
3,session_10,user_2357,2025-05-17 22:11:37,home,tablet,india,direct,75,0,0
4,session_10,user_2357,2025-05-17 22:13:33,product_page,tablet,india,direct,116,0,0

In [13]:
for col in ['page_type', 'device_type', 'country', 'referral_source', 'purchased']:
    print(f"\n--- {col.upper()} ---")
    print(df[col].value_counts())

--- PAGE_TYPE ---
page_type
home            5000
product_page    3987
cart            1599
checkout        1123
confirmation    1010
Name: count, dtype: int64

--- DEVICE_TYPE ---
device_type
mobile     4256
desktop    4240
tablet     4223
Name: count, dtype: int64

--- COUNTRY ---
country
france       1980
uk           1855
canada       1825
usa          1808
india        1794
germany      1738
australia    1719
Name: count, dtype: int64

--- REFERRAL_SOURCE ---
referral_source
google          3304
email           3212
social media    3115
direct          3088
Name: count, dtype: int64

--- PURCHASED ---
purchased
0    7669
1    5050
Name: count, dtype: int64

In [14]:
df['purchased'] = df['purchased'].astype(str).str.strip().str.lower()
df['purchased'] = df['purchased'].replace({
    'true': 1,
    'false': 0,
    'yes': 1,
    'no': 0,
    '1': 1,
    '0': 0})

df['purchased'] = df['purchased'].astype(int)
df['purchased'].value_counts()

C:\Users\HP\AppData\Local\Temp\ipykernel_13096\1916737830.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['purchased'] = df['purchased'].replace({

purchased
0    7669
1    5050
Name: count, dtype: int64

In [15]:
print("Negative time_on_page_seconds:", (df['time_on_page_seconds'] < 0).sum())
print("Negative items_in_cart:", (df['items_in_cart'] < 0).sum())

Negative time_on_page_seconds: 0
Negative items_in_cart: 0

In [16]:
df.loc[df['time_on_page_seconds'] < 0, 'time_on_page_seconds'] = np.nan
df.loc[df['items_in_cart'] < 0, 'items_in_cart'] = np.nan
df[['time_on_page_seconds', 'items_in_cart']].isnull().sum()

time_on_page_seconds    0
items_in_cart           0
dtype: int64

In [17]:
df['date'] = df['timestamp'].dt.date
df['year'] = df['timestamp'].dt.year
df['month'] = df['timestamp'].dt.month
df['month_name'] = df['timestamp'].dt.month_name()
df['day'] = df['timestamp'].dt.day
df['day_name'] = df['timestamp'].dt.day_name()
df['hour'] = df['timestamp'].dt.hour

df.head()

,session_id,user_id,timestamp,page_type,device_type,country,referral_source,time_on_page_seconds,items_in_cart,purchased,date,year,month,month_name,day,day_name,hour
0,session_0,user_2223,2025-01-20 22:53:34,home,desktop,india,social media,55.0,0.0,0,2025-01-20,2025,1,January,20,Monday,22
1,session_1,user_2192,2025-02-26 12:57:10,home,tablet,germany,email,99.0,0.0,0,2025-02-26,2025,2,February,26,Wednesday,12
2,session_1,user_2192,2025-02-26 12:59:11,product_page,tablet,germany,email,121.0,0.0,0,2025-02-26,2025,2,February,26,Wednesday,12
3,session_10,user_2357,2025-05-17 22:11:37,home,tablet,india,direct,75.0,0.0,0,2025-05-17,2025,5,May,17,Saturday,22
4,session_10,user_2357,2025-05-17 22:13:33,product_page,tablet,india,direct,116.0,0.0,0,2025-05-17,2025,5,May,17,Saturday,22

In [18]:
df.to_csv(r"E:\User_Funnel\customer_journey_clean.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [19]:
session_summary = df.groupby('session_id').agg(
    user_id=('user_id', 'first'),
    session_start=('timestamp', 'min'),
    session_end=('timestamp', 'max'),
    total_pages_visited=('page_type', 'count'),
    total_time_spent_seconds=('time_on_page_seconds', 'sum'),
    max_items_in_cart=('items_in_cart', 'max'),
    purchased=('purchased', 'max'),
    device_type=('device_type', 'first'),
    country=('country', 'first'),
    referral_source=('referral_source', 'first')
).reset_index()

session_summary.head()

,session_id,user_id,session_start,session_end,total_pages_visited,total_time_spent_seconds,max_items_in_cart,purchased,device_type,country,referral_source
0,session_0,user_2223,2025-01-20 22:53:34,2025-01-20 22:53:34,1,55.0,0.0,0,desktop,india,social media
1,session_1,user_2192,2025-02-26 12:57:10,2025-02-26 12:59:11,2,220.0,0.0,0,tablet,germany,email
2,session_10,user_2357,2025-05-17 22:11:37,2025-05-17 22:13:33,2,191.0,0.0,0,tablet,india,direct
3,session_100,user_1233,2025-04-02 11:24:36,2025-04-02 11:25:41,2,101.0,1.0,0,desktop,usa,email
4,session_1000,user_1551,2025-08-25 09:34:15,2025-08-25 09:41:24,5,474.0,3.0,1,mobile,france,email

In [20]:
session_summary['session_duration_minutes'] = (
    (session_summary['session_end'] - session_summary['session_start']).dt.total_seconds() / 60
)

session_summary.head()

,session_id,user_id,session_start,session_end,total_pages_visited,total_time_spent_seconds,max_items_in_cart,purchased,device_type,country,referral_source,session_duration_minutes
0,session_0,user_2223,2025-01-20 22:53:34,2025-01-20 22:53:34,1,55.0,0.0,0,desktop,india,social media,0.000000
1,session_1,user_2192,2025-02-26 12:57:10,2025-02-26 12:59:11,2,220.0,0.0,0,tablet,germany,email,2.016667
2,session_10,user_2357,2025-05-17 22:11:37,2025-05-17 22:13:33,2,191.0,0.0,0,tablet,india,direct,1.933333
3,session_100,user_1233,2025-04-02 11:24:36,2025-04-02 11:25:41,2,101.0,1.0,0,desktop,usa,email,1.083333
4,session_1000,user_1551,2025-08-25 09:34:15,2025-08-25 09:41:24,5,474.0,3.0,1,mobile,france,email,7.150000

In [21]:
print("Session Summary Shape:", session_summary.shape)
session_summary.info()

Session Summary Shape: (5000, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   session_id                5000 non-null   object
 1   user_id                   5000 non-null   object
 2   session_start             5000 non-null   datetime64[ns]
 3   session_end               5000 non-null   datetime64[ns]
 4   total_pages_visited       5000 non-null   int64
 5   total_time_spent_seconds  5000 non-null   float64
 6   max_items_in_cart         5000 non-null   float64
 7   purchased                 5000 non-null   int64
 8   device_type               5000 non-null   object
 9   country                   5000 non-null   object
 10  referral_source           5000 non-null   object
 11  session_duration_minutes  5000 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(5)
memory usage: 468.9+ KB

In [24]:
session_summary.to_csv(r"E:\User_Funnel\session_summary.csv", index=False)

print("Session summary saved successfully.")

Session summary saved successfully.

In [25]:
funnel_flags = df.groupby('session_id').agg(
    visited_home=('page_type', lambda x: int('home' in x.values)),
    visited_product_page=('page_type', lambda x: int('product_page' in x.values)),
    visited_cart=('page_type', lambda x: int('cart' in x.values)),
    visited_checkout=('page_type', lambda x: int('checkout' in x.values)),
    visited_confirmation=('page_type', lambda x: int('confirmation' in x.values)),
    purchased=('purchased', 'max')
).reset_index()

funnel_flags.head()

,session_id,visited_home,visited_product_page,visited_cart,visited_checkout,visited_confirmation,purchased
0,session_0,1,0,0,0,0,0
1,session_1,1,1,0,0,0,0
2,session_10,1,1,0,0,0,0
3,session_100,1,1,0,0,0,0
4,session_1000,1,1,1,1,1,1

In [26]:
session_master = session_summary.merge(funnel_flags, on=['session_id', 'purchased'], how='left')
session_master.head()

,session_id,user_id,session_start,session_end,total_pages_visited,total_time_spent_seconds,max_items_in_cart,purchased,device_type,country,referral_source,session_duration_minutes,visited_home,visited_product_page,visited_cart,visited_checkout,visited_confirmation
0,session_0,user_2223,2025-01-20 22:53:34,2025-01-20 22:53:34,1,55.0,0.0,0,desktop,india,social media,0.000000,1,0,0,0,0
1,session_1,user_2192,2025-02-26 12:57:10,2025-02-26 12:59:11,2,220.0,0.0,0,tablet,germany,email,2.016667,1,1,0,0,0
2,session_10,user_2357,2025-05-17 22:11:37,2025-05-17 22:13:33,2,191.0,0.0,0,tablet,india,direct,1.933333,1,1,0,0,0
3,session_100,user_1233,2025-04-02 11:24:36,2025-04-02 11:25:41,2,101.0,1.0,0,desktop,usa,email,1.083333,1,1,0,0,0
4,session_1000,user_1551,2025-08-25 09:34:15,2025-08-25 09:41:24,5,474.0,3.0,1,mobile,france,email,7.150000,1,1,1,1,1

In [27]:
session_master.to_csv(r"E:\User_Funnel\session_master.csv", index=False)

print("Session master table saved successfully.")

Session master table saved successfully.

In [28]:
print("Total Sessions:", session_master['session_id'].nunique())
print("Purchased Sessions:", session_master['purchased'].sum())
print("Conversion Rate %:", round(session_master['purchased'].mean() * 100, 2))

Total Sessions: 5000
Purchased Sessions: 1010
Conversion Rate %: 20.2

In [29]:
print("Visited Home:", session_master['visited_home'].sum())
print("Visited Product Page:", session_master['visited_product_page'].sum())
print("Visited Cart:", session_master['visited_cart'].sum())
print("Visited Checkout:", session_master['visited_checkout'].sum())
print("Visited Confirmation:", session_master['visited_confirmation'].sum())
print("Purchased:", session_master['purchased'].sum())

Visited Home: 5000
Visited Product Page: 3987
Visited Cart: 1599
Visited Checkout: 1123
Visited Confirmation: 1010
Purchased: 1010

In [30]:
view_to_product = session_master['visited_product_page'].sum() / session_master['visited_home'].sum() * 100
product_to_cart = session_master['visited_cart'].sum() / session_master['visited_product_page'].sum() * 100
cart_to_checkout = session_master['visited_checkout'].sum() / session_master['visited_cart'].sum() * 100
checkout_to_confirmation = session_master['visited_confirmation'].sum() / session_master['visited_checkout'].sum() * 100
overall_conversion = session_master['purchased'].sum() / session_master['visited_home'].sum() * 100

print("Home → Product Page %:", round(view_to_product, 2))
print("Product Page → Cart %:", round(product_to_cart, 2))
print("Cart → Checkout %:", round(cart_to_checkout, 2))
print("Checkout → Confirmation %:", round(checkout_to_confirmation, 2))
print("Overall Conversion %:", round(overall_conversion, 2))

Home → Product Page %: 79.74
Product Page → Cart %: 40.11
Cart → Checkout %: 70.23
Checkout → Confirmation %: 89.94
Overall Conversion %: 20.2

In [32]:
view_to_product = session_master['visited_product_page'].sum() / session_master['visited_home'].sum() * 100
product_to_cart = session_master['visited_cart'].sum() / session_master['visited_product_page'].sum() * 100
cart_to_checkout = session_master['visited_checkout'].sum() / session_master['visited_cart'].sum() * 100
checkout_to_confirmation = session_master['visited_confirmation'].sum() / session_master['visited_checkout'].sum() * 100
overall_conversion = session_master['purchased'].sum() / session_master['visited_home'].sum() * 100

print("Home → Product Page %:", round(view_to_product, 2))
print("Product Page → Cart %:", round(product_to_cart, 2))
print("Cart → Checkout %:", round(cart_to_checkout, 2))
print("Checkout → Confirmation %:", round(checkout_to_confirmation, 2))
print("Overall Conversion %:", round(overall_conversion, 2))

Home → Product Page %: 79.74
Product Page → Cart %: 40.11
Cart → Checkout %: 70.23
Checkout → Confirmation %: 89.94
Overall Conversion %: 20.2

In [34]:
funnel_summary = pd.DataFrame({
    'stage': ['home', 'product_page', 'cart', 'checkout', 'confirmation', 'purchased'],
    'sessions': [
        session_master['visited_home'].sum(),
        session_master['visited_product_page'].sum(),
        session_master['visited_cart'].sum(),
        session_master['visited_checkout'].sum(),
        session_master['visited_confirmation'].sum(),
        session_master['purchased'].sum() ]})
funnel_summary

          stage  sessions
0          home      5000
1  product_page      3987
2          cart      1599
3      checkout      1123
4  confirmation      1010
5     purchased      1010

In [35]:
funnel_summary.to_csv(r"E:\User_Funnel\funnel_summary.csv", index=False)
print("Funnel summary saved successfully.")

Funnel summary saved successfully.